/**
 * MimicAPI — shared/openapi-builder.js
 *
 * Converts an array of endpoint entries (from CaptureStore.getEndpoints())
 * into a valid OpenAPI 3.0.3 specification object.
 *
 * Zero external dependencies — pure JS.
 * Converts to YAML using a hand-rolled serialiser so the server
 * can also use it without importing js-yaml at the extension level.
 *
 * Usage:
 *   import { buildSpec, specToYAML } from '../shared/openapi-builder.js'
 *   const spec = buildSpec('https://api.example.com', endpoints)
 *   const yaml = specToYAML(spec)
 */

import { inferSchema, mergeSchemas } from './schema-infer.js'

// ─── Main builder ────────────────────────────────────────────────────────────

/**
 * @param {string} baseUrl   - e.g. 'https://api.example.com'
 * @param {Array}  endpoints - from CaptureStore.getEndpoints()
 * @returns {object} OpenAPI 3.0.3 spec object
 */
export function buildSpec(baseUrl, endpoints) {
  let origin
  try {
    origin = new URL(baseUrl).origin
  } catch {
    origin = baseUrl
  }

  const paths = {}

  for (const ep of endpoints) {
    const { method, templatedUrl, samples } = ep

    // Convert full URL path to relative path for the spec
    let path
    try {
      path = decodeURIComponent(new URL(templatedUrl).pathname)
    } catch {
      path = templatedUrl
    }

    if (!paths[path]) paths[path] = {}

    const verb        = method.toLowerCase()
    const parameters  = extractPathParams(path)

    // Extract query parameters from sample URLs
    const queryParams = extractQueryParams(samples)
    if (queryParams.length > 0) parameters.push(...queryParams)

    const statusCodes = [...new Set(samples.map(s => s.status).filter(Boolean))]

    // Merge all response bodies for the primary (most common) status code
    const primaryStatus = pickPrimaryStatus(statusCodes)
    const primarySamples = samples
      .filter(s => s.status === primaryStatus && s.responseBody != null)
      .map(s => s.responseBody)

    const responseSchema = primarySamples.length > 0
      ? mergeSchemas(primarySamples.map(inferSchema))
      : null

    // Request body schema from POST/PUT/PATCH samples
    const hasBody      = ['post', 'put', 'patch'].includes(verb)
    const reqBodies    = samples.map(s => s.requestBody).filter(b => b != null)
    const requestSchema = (hasBody && reqBodies.length > 0)
      ? mergeSchemas(reqBodies.map(inferSchema))
      : null

    const operation = {
      summary:    `${method} ${path}`,
      parameters: parameters.length > 0 ? parameters : undefined,
      responses:  buildResponses(statusCodes, primaryStatus, responseSchema),
    }

    if (requestSchema) {
      operation.requestBody = {
        required: true,
        content: {
          'application/json': { schema: requestSchema },
        },
      }
    }

    paths[path][verb] = operation
  }

  return {
    openapi: '3.0.3',
    info: {
      title:   `${origin} API`,
      version: '1.0.0',
      description: `Auto-generated by MimicAPI from recorded traffic. ` +
                   `Review and refine before production use.`,
    },
    servers: [{ url: origin }],
    paths,
  }
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function extractPathParams(path) {
  const params = []
  const regex  = /\{([^}]+)\}/g
  let match
  while ((match = regex.exec(path)) !== null) {
    params.push({
      name:     match[1],
      in:       'path',
      required: true,
      schema:   { type: 'string' },
    })
  }
  return params
}

/**
 * Extract query parameters from sample URLs.
 * Collects all unique param names across all samples,
 * infers example values, and produces `in: query` params.
 */
function extractQueryParams(samples) {
  const paramMap = new Map()  // name → Set of values

  for (const s of samples) {
    if (!s.url) continue
    try {
      const u = new URL(s.url)
      for (const [key, value] of u.searchParams) {
        if (!paramMap.has(key)) paramMap.set(key, new Set())
        paramMap.get(key).add(value)
      }
    } catch {
      // skip malformed URLs
    }
  }

  const params = []
  for (const [name, values] of paramMap) {
    const example = [...values][0]
    // Infer simple type from the first value
    let schema = { type: 'string' }
    if (example !== undefined) {
      if (/^\d+$/.test(example))              schema = { type: 'integer', example: parseInt(example) }
      else if (/^\d+\.\d+$/.test(example))    schema = { type: 'number',  example: parseFloat(example) }
      else if (/^(true|false)$/i.test(example)) schema = { type: 'boolean', example: example === 'true' }
      else                                     schema = { type: 'string',  example }
    }
    params.push({ name, in: 'query', required: false, schema })
  }

  return params
}

function pickPrimaryStatus(statusCodes) {
  // Prefer 200, then first 2xx, then whatever we have
  if (statusCodes.includes(200)) return 200
  const twoxx = statusCodes.find(s => s >= 200 && s < 300)
  return twoxx ?? statusCodes[0] ?? 200
}

function buildResponses(statusCodes, primaryStatus, responseSchema) {
  const responses = {}

  for (const code of statusCodes) {
    const stringCode = String(code)
    if (code === primaryStatus && responseSchema) {
      responses[stringCode] = {
        description: httpStatusText(code),
        content: {
          'application/json': { schema: responseSchema },
        },
      }
    } else {
      responses[stringCode] = { description: httpStatusText(code) }
    }
  }

  if (Object.keys(responses).length === 0) {
    responses['200'] = { description: 'OK' }
  }

  return responses
}

function httpStatusText(code) {
  const map = {
    200: 'OK', 201: 'Created', 204: 'No Content',
    400: 'Bad Request', 401: 'Unauthorized', 403: 'Forbidden',
    404: 'Not Found', 409: 'Conflict', 422: 'Unprocessable Entity',
    429: 'Too Many Requests', 500: 'Internal Server Error',
  }
  return map[code] ?? `HTTP ${code}`
}

// ─── YAML serialiser ─────────────────────────────────────────────────────────

/**
 * Minimal YAML serialiser for OpenAPI spec objects.
 * Handles: string, number, boolean, null, array, object.
 * No external dependencies.
 */
export function specToYAML(obj, indent = 0) {
  const pad = '  '.repeat(indent)

  if (obj === null || obj === undefined) return 'null'
  if (typeof obj === 'boolean')          return String(obj)
  if (typeof obj === 'number')           return String(obj)

  if (typeof obj === 'string') {
    // Quote strings that contain YAML special chars or look like booleans/numbers
    const needsQuotes =
      /[:#\[\]{},&*?|<>=!%@`]/.test(obj) ||
      /^(true|false|null|yes|no|on|off)$/i.test(obj) ||
      /^\d/.test(obj) ||
      obj.includes('\n')
    return needsQuotes ? `"${obj.replace(/"/g, '\\"')}"` : obj
  }

  if (Array.isArray(obj)) {
    if (obj.length === 0) return '[]'
    return obj.map(item => {
      const val = specToYAML(item, indent + 1)
      const firstLine = val.split('\n')[0]
      if (typeof item === 'object' && item !== null && !Array.isArray(item)) {
        return `${pad}-\n${specToYAML(item, indent + 1)}`
      }
      return `${pad}- ${val}`
    }).join('\n')
  }

  if (typeof obj === 'object') {
    const entries = Object.entries(obj).filter(([, v]) => v !== undefined)
    if (entries.length === 0) return ''
    return entries.map(([key, value]) => {
      const yamlKey = /[^a-zA-Z0-9_\-/{}]/.test(key) ? `"${key}"` : key
      if (value === null || typeof value !== 'object') {
        return `${pad}${yamlKey}: ${specToYAML(value, indent)}`
      }
      if (Array.isArray(value) && value.length === 0) {
        return `${pad}${yamlKey}: []`
      }
      return `${pad}${yamlKey}:\n${specToYAML(value, indent + 1)}`
    }).join('\n')
  }

  return String(obj)
}
